import 'tippy.js/dist/tippy.css'
import { HelpIcon, KeyboardIcon, LanguageIcon, LogoutIcon, ProfileIcon, SettingIcon } from '~/components/Icons'

export const discovers = [
    {
        id: 1,
        title: 'Jiggle Jiggle - Duke & Jones & Louis Theroux',
        type: 'video',
    },
    {
        id: 2,
        title: 'tiktok-1sw5kok-PText eikhr9j12',
        type: 'video',
    },
    {
        id: 3,
        title: '我是女王',
        type: 'video',
    },
    {
        id: 4,
        title: '墨鏡搖擺',
        type: 'text',
    },
    {
        id: 5,
        title: '濃情粽意',
        type: 'text',
    },
    {
        id: 6,
        title: '交誼舞',
        type: 'text',
    },

    {
        id: 7,
        title: 'FEARLESS - LE SSERAFIM',
        type: 'video',
    },
    {
        id: 8,
        title: '濃情粽意',
        type: 'text',
    },
    {
        id: 9,
        title: '  TOMBOY - (G)I-DLE',
        type: 'video',
    },
]

export const floowingUsers = [
    {
        id: 1,
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-useast2a-avt-0068-giso/cecb376e20a5ecb89516762f29e152fb~c5_100x100.jpeg?x-expires=1654786800&x-signature=BwIUuWyGyoh4br76GBhii%2BFL0uQ%3D',
        full_name: 'tonyun_',
        nickname: '云☁️',
        isLive: true,
        tick: false,
        followers: '163.1M',
        likes: '200.1M',
    },
    {
        id: 2,
        avatar: 'https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/596d5503f84e277f330e05f480d77036.jpeg?x-expires=1654786800&x-signature=70fQsZhMVXSekMYxYMwELrLX4iI%3D',
        full_name: 'haryluthfi21____',
        nickname: '💥 💫🍃 21- 𝕁𝕦ℕ𝕚- 90🍃💫',
        isLive: true,
        tick: false,
        followers: '11.1M',
        likes: '102.2M',
    },
    {
        id: 3,
        avatar: 'https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/d5272da1aa6823116b61a061d9acb473.jpeg?x-expires=1654786800&x-signature=RUdXVdIlg53dJbQcAKSPmkMQRU4%3D',
        full_name: 'cia.hartono',
        nickname: 'Cia☁️🐝',
        isLive: false,
        tick: false,
        followers: '11.1M',
        likes: '111.2M',
    },
    {
        id: 4,
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-useast2a-avt-0068-giso/d9fe657b9f966af846bd1b1265f9f9fe~c5_100x100.jpeg?x-expires=1654786800&x-signature=zjL6MbMvFTxPB%2FAj4nD9bNAnfGM%3D',
        full_name: 'shanwei153',
        nickname: 'Sharon🇹🇼',
        isLive: true,
        tick: false,
        followers: '112K',
        likes: '589.1K',
    },
    {
        id: 5,
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-useast2a-avt-0068-giso/af819567cc765c0ecd68ef39c9ddac92~c5_100x100.jpeg?x-expires=1654786800&x-signature=7nWGitLaIJdoeKENBP5RGmodd2g%3D',
        full_name: 'musingxer',
        nickname: '木星人MuSingxer 🌟',
        isLive: false,
        tick: true,
        followers: '112K',
        likes: '290.1K',
    },
    {
        id: 6,
        avatar: 'https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/e7a084ab3c565142f5bfe2196ca68785.jpeg?x-expires=1654786800&x-signature=zqiqCX4Gf9KpwGn6aJDbkd9eZNA%3D',
        full_name: 'neneko.n',
        nickname: '✨ Neneko ✨',
        isLive: true,
        tick: false,
        followers: '632K',
        likes: '1.1M',
    },
    {
        id: 7,
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-useast2a-avt-0068-giso/c233133ca639393d13947c420ec84ff3~c5_100x100.jpeg?x-expires=1654786800&x-signature=oBrh807Y%2F9Hd%2FBoe5Jz%2FXg8Tpe4%3D',
        full_name: 'janie.lin',
        nickname: '泥泥Janie🇹🇼🇯🇵ˣ🇲🇾',
        isLive: false,
        tick: false,
        followers: '324M',
        likes: '1029.1M',
    },
    {
        id: 8,
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-useast2a-avt-0068-giso/f2446d9f9ed29a0e04e963f7dda71fdd~c5_100x100.jpeg?x-expires=1654786800&x-signature=b2o7NXstM2qRUgOLHHox2i%2FJPYA%3D',
        full_name: 'junya1gou.jr',
        nickname: 'junya jr.&Mask🎭/こじゅんや',
        isLive: true,
        tick: false,
        followers: '412.1K',
        likes: '653.3K',
    },
    {
        id: 9,
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-useast2a-avt-0068-giso/f43f9124aa9dd610423a8aecccf06f92~c5_100x100.jpeg?x-expires=1654786800&x-signature=wUoddbJUgXH1hSjGw2Y%2FlbWpetA%3D',
        full_name: 'vangiang7992',
        nickname: 'Streetfood🌍',
        isLive: false,
        tick: true,
        followers: '322.4K',
        likes: '432.1M',
    },
    {
        id: 10,
        avatar: 'https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/6de6fd6edb276342649d1eeb6948485e.jpeg?x-expires=1654786800&x-signature=YSOFuB1IcqvN3WI3JRv4PdV1%2Fnk%3D',
        full_name: 'vieazkhanza05',
        nickname: '🐾𝔼_𝕧𝕚𝕖𝟘𝟝🐾',
        isLive: false,
        tick: false,
        followers: '214K',
        likes: '425.2K',
    },
    {
        id: 11,
        avatar: 'https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/0983cf9be053097a780de7b6e44eedbe.jpeg?x-expires=1654790400&x-signature=YM%2BP23jjxGE4HY3ml4tZVPTr21Q%3D',
        full_name: 'brick_grandpa',
        nickname: '벽돌할아버지',
        isLive: false,
        tick: false,
        followers: '110.4M',
        likes: '351.5M',
    },
    {
        id: 12,
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-useast2a-avt-0068-aiso/b4e9efd9a474a87f25ddb1ab68dc6881~c5_100x100.jpeg?x-expires=1654786800&x-signature=1aT1O2O%2FJN5Jf07tUMf30V%2ByJZk%3D',
        full_name: 'bitch_089457',
        nickname: '鴛鴦蝴蝶夢',
        isLive: false,
        tick: true,
        followers: '112.1K',
        likes: '1.2M',
    },
    {
        id: 13,
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-useast2a-avt-0068-giso/9d25ee8a69ad2d0fafabced1ccb511d4~c5_100x100.jpeg?x-expires=1654786800&x-signature=7BaCaf%2BOos8arLSkjgF3HytN2QE%3D',
        full_name: 'wei.piano',
        nickname: '威猛叔叔Piano🍍',
        isLive: false,
        tick: false,
        followers: '1.1K',
        likes: '126.1K',
    },
    {
        id: 14,
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/ae812686c8149ca9363ea773089d21ad~c5_100x100.jpeg?x-expires=1654786800&x-signature=aj388ewMFDrff3llju9R6Ytw%2Bzs%3D',
        full_name: 'jinxly8',
        nickname: '🌹遇鉴藏友Collect the world',
        isLive: false,
        tick: false,
        followers: '11.1M',
        likes: '127.4M',
    },
    {
        id: 15,
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-useast2a-avt-0068-giso/4869b227d823078669edf37049925be5~c5_100x100.jpeg?x-expires=1654786800&x-signature=pEApsWgUjKtDsyC61WtCHiX%2FTTc%3D',
        full_name: 'userlkyez1utjn',
        nickname: '曾經滄海💸',
        isLive: false,
        tick: false,
        followers: '1298K',
        likes: '1029.1K',
    },
]
export const UNLOGIN_MENU_ITEM = [
    {
        data: [
            {
                title: 'English',
                icon: <LanguageIcon />,
                children: {
                    title: 'languages',
                    data: [
                        { title: 'English' },
                        { title: 'VietNam' },
                        { title: 'Chinese' },
                        { title: 'Cebuano (Pilipinas)' },
                        { title: 'English' },
                        { title: 'VietNam' },
                        { title: 'Chinese' },
                        { title: 'Cebuano (Pilipinas)' },
                        { title: 'English' },
                        { title: 'VietNam' },
                        { title: 'Chinese' },
                        { title: 'Cebuano (Pilipinas)' },
                        { title: 'English' },
                        { title: 'VietNam' },
                        { title: 'Chinese' },
                        { title: 'Cebuano (Pilipinas)' },
                        { title: 'English' },
                        { title: 'VietNam' },
                        { title: 'Chinese' },
                        { title: 'Cebuano (Pilipinas)' },
                        { title: 'English' },
                        { title: 'VietNam' },
                        { title: 'Chinese' },
                        { title: 'Cebuano (Pilipinas)' },
                    ],
                },
            },
            { title: 'Feedback and help', icon: <HelpIcon />, to: './' },
            { title: 'Keyboard shortcuts', icon: <KeyboardIcon /> },
        ],
    },
]
export const LOGIN_MENU_ITEM = [
    {
        data: [
            { title: 'View profile', icon: <ProfileIcon />, to: './' },
            { title: 'Setting', icon: <SettingIcon />, to: './' },
            ...UNLOGIN_MENU_ITEM[0].data, //clone data from unlogin menu
            { title: 'Log out', icon: <LogoutIcon />, to: './', separate: true },
        ],
    },
]

export const footerData = [
    {
        id: 1,
        data: [
            { id: 1, title: 'About' },
            { id: 2, title: 'Newsroom' },
            { id: 3, title: 'Contact' },
            { id: 4, title: 'Career' },
            { id: 5, title: 'ByteDance' },
        ],
    },
    {
        id: 2,
        data: [
            { id: 1, title: 'TikTok for Good' },
            { id: 2, title: 'Advertise' },
            { id: 3, title: 'Developers' },
            { id: 4, title: 'Transparence' },
            { id: 5, title: 'TikTok Rewards' },
        ],
    },
    {
        id: 3,
        data: [
            { id: 1, title: 'Help' },
            { id: 2, title: 'Safety' },
            { id: 3, title: 'Terms' },
            { id: 4, title: 'Privacy' },
            { id: 5, title: 'Creator Portal' },
        ],
    },
]
